# Home-Manager Konfiguration
# Nachbau aller User-Configs vom Fedora Sway Spin Setup
#
# Aktivierung:
#   1. home-manager installieren (standalone oder als NixOS-Modul)
#   2. Diese Datei nach ~/.config/home-manager/home.nix kopieren
#   3. home-manager switch

{ config, pkgs, ... }:

{
  home.username = "laptop";
  home.homeDirectory = "/home/laptop";
  home.stateVersion = "24.11";

  programs.home-manager.enable = true;

  # ============================================================
  # Bash
  # ============================================================
  programs.bash = {
    enable = true;
    enableCompletion = true;
    initExtra = ''
      set -o vi
      export PS1="\u@$(hostname -I | awk '{print $1}'):\w\$ "
    '';
    profileExtra = ''
      if [ -f "$HOME/.cargo/env" ]; then
        . "$HOME/.cargo/env"
      fi
    '';
  };

  # ============================================================
  # Git
  # ============================================================
  programs.git = {
    enable = true;
  };

  # ============================================================
  # Neovim
  # ============================================================
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    extraLuaConfig = ''
      -- === Basic Neovim setup ===
      vim.opt.number = true
      vim.opt.relativenumber = true
      vim.opt.mouse = "a"

      -- === System clipboard integration ===
      vim.opt.clipboard = "unnamedplus"

      -- Plugin-Manager laden
      local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
      if vim.loop.fs_stat(lazypath) then
        vim.opt.rtp:prepend(lazypath)
      else
        vim.notify("WARN: lazy.nvim nicht gefunden.", vim.log.levels.WARN)
      end

      require("lazy").setup({
        { "lervag/vimtex" },
      })

      -- VimTeX-Konfiguration
      vim.g.vimtex_compiler_method = 'latexmk'
      vim.g.vimtex_compiler_latexmk = {
          executable = 'latexmk',
          options = {
              '-pdf',
              '-interaction=nonstopmode',
              '-synctex=1',
              '-pvc',
          },
      }
      vim.g.vimtex_view_method = 'general'
      vim.g.vimtex_view_general_viewer = 'okular'
    '';
  };

  # ============================================================
  # Foot Terminal
  # ============================================================
  xdg.configFile."foot/foot.ini".text = ''
    # Auto-generated by theme-toggle.sh — light mode
    [main]
    font=JetBrains Mono:size=11
    pad=12x12
    dpi-aware=yes

    [colors]
    background=eff1f5
    foreground=4c4f69
    cursor=4c4f69 eff1f5

    regular0=bcc0cc
    regular1=6c6f85
    regular2=8c8fa1
    regular3=5c5f77
    regular4=9ca0b0
    regular5=acb0be
    regular6=8c8fa1
    regular7=5c5f77

    bright0=acb0be
    bright1=4c4f69
    bright2=5c5f77
    bright3=4c4f69
    bright4=6c6f85
    bright5=9ca0b0
    bright6=5c5f77
    bright7=6c6f85
  '';

  # ============================================================
  # Sway Config
  # ============================================================
  xdg.configFile."sway/config".text = ''
    # Sway Config (migriert von Fedora Sway Spin)

    ### Variables
    font pango: 'Inter' 10

    set $mod Mod4
    set $left h
    set $down j
    set $up k
    set $right l
    set $term foot
    set $rofi_cmd rofi \
            -terminal '$term'
    set $menu $rofi_cmd -show combi -combi-modes drun#run -theme ~/.config/rofi/config.rasi
    set $browser brave
    exec $browser --no-startup-window
    set $Dateimanager thunar

    ### Output
    output HDMI-A-1 resolution 1920x1080 position 0,0

    # Gaps (macOS-style)
    gaps inner 6
    gaps outer 3

    # Borders (schmal, modern)
    default_border pixel 2
    default_floating_border pixel 2

    # Abgerundete Ecken (swayfx)
    corner_radius 8

    # Window Colors
    include ~/.config/sway/theme

    # Waybar (restart bei Reload)
    exec_always bash -c 'killall waybar 2>/dev/null; sleep 0.3; waybar &'

    # Sysinfo-Wallpaper-Updater
    exec ~/Skripte/wallpaper-sysinfo.sh

    # Projekte-Panel
    exec python3 ~/Skripte/projects-panel.py

    # Monitor-lid Erkennung
    exec_always --no-startup-id ~/Skripte/monitor-lid.sh

    ### Input
    input * {
        xkb_layout de
    }

    input type:keyboard {
        xkb_options caps:escape
    }

    ### Key bindings
    bindsym $mod+q kill

    # Terminal
    bindsym $mod+Return exec ~/Skripte/split_toggle.sh $term

    # Browser
    bindsym $mod+b exec ~/Skripte/split_toggle.sh $browser

    # Anki (nativ)
    bindsym $mod+a exec ~/Skripte/split_toggle.sh anki

    # Dateimanager
    bindsym $mod+v exec ~/Skripte/split_toggle.sh $Dateimanager

    # Launcher
    bindsym $mod+d exec ~/Skripte/split_toggle.sh $menu

    # Clipboard Cleaner
    bindsym $mod+Shift+v exec --no-startup-id ~/Skripte/clipboard_cleaner.sh toggle

    # Dejure
    bindsym $mod+p exec ~/Skripte/split_toggle.sh ~/Skripte/open_dejure.sh

    # Screenshot
    bindsym F2 exec grim -g "$(slurp)" - | wl-copy

    floating_modifier $mod normal
    bindsym $mod+Shift+c reload
    bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'

    # Focus
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    bindsym $mod+Left workspace prev
    bindsym $mod+Right workspace next

    # Move windows
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

    # Workspaces
    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    bindsym $mod+5 workspace number 5
    bindsym $mod+6 workspace number 6
    bindsym $mod+7 workspace number 7
    bindsym $mod+8 workspace number 8
    bindsym $mod+9 workspace number 9
    bindsym $mod+0 workspace number 10
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Shift+6 move container to workspace number 6
    bindsym $mod+Shift+7 move container to workspace number 7
    bindsym $mod+Shift+8 move container to workspace number 8
    bindsym $mod+Shift+9 move container to workspace number 9
    bindsym $mod+Shift+0 move container to workspace number 10

    # Layout
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split
    bindsym $mod+f fullscreen
    bindsym $mod+Shift+space floating toggle
    bindsym $mod+space focus mode_toggle

    # Scratchpad
    bindsym $mod+Shift+minus move scratchpad
    bindsym $mod+minus scratchpad show

    # Resize
    mode "resize" {
        bindsym $left resize shrink width 10px
        bindsym $down resize grow height 10px
        bindsym $up resize shrink height 10px
        bindsym $right resize grow width 10px
        bindsym Left resize shrink width 10px
        bindsym Down resize grow height 10px
        bindsym Up resize shrink height 10px
        bindsym Right resize grow width 10px
        bindsym Return mode "default"
        bindsym Escape mode "default"
    }
    bindsym $mod+r mode "resize"

    # Custom
    bindsym $mod+Shift+Escape exec ~/Skripte/lock.sh && systemctl suspend
    bindsym $mod+Shift+Escape+q exec systemctl hibernate

    seat seat0 xcursor_theme "Bibata-Modern-Classic" 20
  '';

  # ============================================================
  # Sway Theme (light mode default)
  # ============================================================
  xdg.configFile."sway/theme".text = ''
    # Auto-generated by theme-toggle.sh — light mode
    client.focused          #5c5f77 #eff1f5 #4c4f69 #5c5f77 #5c5f77
    client.focused_inactive #bcc0cc #eff1f5 #6c6f85 #bcc0cc #bcc0cc
    client.unfocused        #ccd0da #eff1f5 #acb0be #ccd0da #ccd0da
    client.urgent           #4c4f69 #eff1f5 #4c4f69 #4c4f69 #4c4f69
  '';

  # ============================================================
  # Waybar
  # ============================================================
  xdg.configFile."waybar/config".text = builtins.toJSON {
    layer = "top";
    position = "top";
    margin-top = 4;
    margin-left = 12;
    margin-right = 12;

    modules-left = [ "sway/workspaces" "sway/mode" ];
    modules-center = [ "clock" ];
    modules-right = [ "custom/dnd" "bluetooth" "network" "battery" "custom/theme" ];

    "sway/workspaces" = {
      disable-scroll = true;
      all-outputs = true;
      format = "{name}";
    };

    "sway/mode" = { format = "{}"; };

    clock = {
      format = "{:%H:%M}";
      format-alt = "{:%A, %e. %B %Y}";
      tooltip-format = "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>";
    };

    bluetooth = {
      format-connected = "{device_alias}";
      format-on = "";
      format-off = "";
      format-disabled = "";
      tooltip-format-connected = "{device_enumerate}";
      tooltip-format-enumerate-connected = "{device_alias}";
    };

    network = {
      format-wifi = "{essid}";
      format-ethernet = "LAN";
      format-linked = "LAN";
      format-disconnected = "Offline";
      format-alt = "{ipaddr}/{cidr}";
      tooltip-format-wifi = "{ifname} @ {essid}\nIP: {ipaddr}\nSignal: {signalStrength}%";
    };

    battery = {
      interval = 5;
      states = { warning = 20; critical = 10; };
      format = "{capacity}%";
      format-charging = "{capacity}%+";
      format-plugged = "{capacity}%";
      tooltip-format = "{time} remaining";
    };

    "custom/dnd" = {
      format = "{}";
      return-type = "json";
      exec = "if [ \"$(dunstctl is-paused)\" = true ]; then printf '{\"text\":\"\\u25CF\",\"class\":\"on\"}'; else printf '{\"text\":\"\\u25CB\",\"class\":\"off\"}'; fi";
      interval = 2;
      on-click = "dunstctl set-paused toggle";
      tooltip = false;
    };

    "custom/theme" = {
      format = "{}";
      exec = "[ \"$(cat ~/.config/theme-mode 2>/dev/null)\" = light ] && printf '\\u2600' || printf '\\u263E'";
      interval = 2;
      on-click = "~/Skripte/theme-toggle.sh";
      tooltip = false;
    };
  };

  xdg.configFile."waybar/style.css".text = ''
    /* Auto-generated by theme-toggle.sh — light mode */
    * {
        font-family: "Inter";
        font-size: 13px;
        border: none;
        border-radius: 0;
        min-height: 0;
        margin: 0;
        padding: 0;
    }

    #waybar {
        background: transparent;
        color: #5c5f77;
    }

    #workspaces button {
        background: transparent;
        color: #9ca0b0;
        padding: 0 6px;
        margin: 4px 1px;
        border-radius: 0;
        font-size: 13px;
    }

    #workspaces button.focused {
        color: #4c4f69;
        font-weight: 600;
    }

    #workspaces button.urgent {
        color: #4c4f69;
        text-decoration: underline;
    }

    #workspaces button:hover {
        color: #4c4f69;
    }

    #mode {
        color: #4c4f69;
        font-style: italic;
        padding: 0 8px;
        margin: 4px 0;
    }

    #clock {
        font-weight: 600;
        color: #4c4f69;
        padding: 0 12px;
        margin: 4px 2px;
    }

    #bluetooth,
    #network,
    #battery,
    #custom-theme {
        padding: 0 8px;
        margin: 4px 0;
    }

    #network.disconnected {
        color: #9ca0b0;
    }

    #battery.charging,
    #battery.plugged {
        color: #4c4f69;
    }

    #battery.warning:not(.charging) {
        color: #6c6f85;
        font-weight: 600;
    }

    #battery.critical:not(.charging) {
        color: #4c4f69;
        font-weight: 700;
    }

    #custom-theme {
        font-size: 15px;
        padding: 0 6px;
        margin: 4px 4px;
    }

    tooltip {
        background: #eff1f5;
        border: 1px solid #bcc0cc;
        border-radius: 8px;
    }

    tooltip label {
        color: #4c4f69;
        padding: 4px 8px;
    }
  '';

  # ============================================================
  # Dunst
  # ============================================================
  xdg.configFile."dunst/dunstrc".text = ''
    # Auto-generated by theme-toggle.sh — light mode

    [global]
        follow = mouse
        width = 320
        height = (0, 120)
        origin = top-right
        offset = (12, 12)
        notification_limit = 5

        progress_bar = true
        progress_bar_height = 8
        progress_bar_frame_width = 1
        progress_bar_min_width = 150
        progress_bar_max_width = 300

        indicate_hidden = yes
        shrink = no
        separator_height = 2
        separator_color = "#ccd0da"
        padding = 16
        horizontal_padding = 16
        text_icon_padding = 16

        frame_width = 1
        frame_color = "#bcc0cc"
        corner_radius = 12

        sort = yes
        idle_threshold = 120

        font = Inter 10
        line_height = 0
        markup = full
        format = "<b>%s</b>\n%b"
        alignment = left
        vertical_alignment = center
        show_age_threshold = 60
        word_wrap = yes
        ellipsize = middle
        ignore_newline = no
        stack_duplicates = true
        hide_duplicate_count = false
        show_indicators = yes

        icon_position = left
        min_icon_size = 32
        max_icon_size = 48

        mouse_left_click = close_current
        mouse_middle_click = do_action, close_current
        mouse_right_click = close_all

    [urgency_low]
        background = "#eff1f5"
        foreground = "#4c4f69"
        frame_color = "#ccd0da"
        timeout = 5

    [urgency_normal]
        background = "#eff1f5"
        foreground = "#4c4f69"
        frame_color = "#5c5f77"
        timeout = 8

    [urgency_critical]
        background = "#eff1f5"
        foreground = "#4c4f69"
        frame_color = "#4c4f69"
        timeout = 0
  '';

  # ============================================================
  # Rofi
  # ============================================================
  xdg.configFile."rofi/config.rasi".text = ''
    /* Auto-generated by theme-toggle.sh */

    configuration {
        show-icons:      true;
        display-drun:    "";
        disable-history: false;
    }
    * {
        font: "JetBrains Mono 12";
        foreground: #4c4f69;
        background-color: #eff1f5;
        active-background: #5c5f77;
        urgent-background: #4c4f69;
        urgent-foreground: #eff1f5;
        selected-background: #bcc0cc;
        selected-urgent-background: @urgent-background;
        selected-active-background: @active-background;
        separatorcolor: #ccd0da;
        bordercolor: #5c5f77;
    }

    #window {
        background-color: @background-color;
        border:           2;
        border-radius:    12;
        border-color:     @bordercolor;
        padding:          20;
    }
    #mainbox {
        border:  0;
        padding: 0;
    }
    #message {
        border:       0px;
        border-color: @separatorcolor;
        padding:      1px;
    }
    #textbox {
        text-color: @foreground;
    }
    #listview {
        fixed-height: 0;
        border:       0px;
        border-color: @separatorcolor;
        spacing:      4px;
        scrollbar:    false;
        padding:      8px 0px 0px;
    }
    #element {
        border:  0;
        padding: 6px 8px;
        border-radius: 8;
    }
    #element.normal.normal {
        background-color: @background-color;
        text-color:       @foreground;
    }
    #element.normal.urgent {
        background-color: @urgent-background;
        text-color:       @urgent-foreground;
    }
    #element.normal.active {
        background-color: #ccd0da;
        text-color:       @foreground;
    }
    #element.selected.normal {
        background-color: @selected-background;
        text-color:       @foreground;
    }
    #element.selected.urgent {
        background-color: @selected-urgent-background;
        text-color:       @foreground;
    }
    #element.selected.active {
        background-color: @selected-active-background;
        text-color:       #eff1f5;
    }
    #element.alternate.normal {
        background-color: @background-color;
        text-color:       @foreground;
    }
    #element.alternate.urgent {
        background-color: @urgent-background;
        text-color:       @foreground;
    }
    #element.alternate.active {
        background-color: #ccd0da;
        text-color:       @foreground;
    }
    #scrollbar {
        width:        2px;
        border:       0;
        handle-width: 8px;
        padding:      0;
    }
    #sidebar {
        border:       2px dash 0px 0px;
        border-color: @separatorcolor;
    }
    #button.selected {
        background-color: @selected-background;
        text-color:       @foreground;
    }
    #inputbar {
        spacing:    0;
        text-color: @foreground;
        padding:    4px 4px;
        border:     0 0 1px 0;
        border-color: #ccd0da;
    }
    #case-indicator {
        spacing:    0;
        text-color: @foreground;
    }
    #entry {
        spacing:    0;
        text-color: @foreground;
    }
    #prompt {
        spacing:    0;
        text-color: #5c5f77;
    }
    #inputbar {
        children:   [ prompt,textbox-prompt-colon,entry,case-indicator ];
    }
    #textbox-prompt-colon {
        expand:     false;
        str:        ">";
        margin:     0px 0.3em 0em 0em;
        text-color: #9ca0b0;
    }
    element-text, element-icon {
        background-color: inherit;
        text-color: inherit;
    }
  '';

  # ============================================================
  # Swaylock
  # ============================================================
  xdg.configFile."swaylock/config".text = ''
    daemonize
    ignore-empty-password
    show-failed-attempts

    # Catppuccin Mocha colors
    inside-color=1e1e2e00
    inside-clear-color=1e1e2e00
    inside-ver-color=1e1e2e00
    inside-wrong-color=1e1e2e00

    ring-color=585b70
    ring-clear-color=a6e3a1
    ring-ver-color=89b4fa
    ring-wrong-color=f38ba8

    key-hl-color=cdd6f4
    bs-hl-color=f38ba8

    text-color=cdd6f4
    text-clear-color=a6e3a1
    text-ver-color=89b4fa
    text-wrong-color=f38ba8

    line-color=00000000
    line-clear-color=00000000
    line-ver-color=00000000
    line-wrong-color=00000000

    separator-color=00000000

    indicator-radius=80
    indicator-thickness=8
  '';

  # ============================================================
  # Brave Flags
  # ============================================================
  xdg.configFile."brave-flags.conf".text = ''
    --enable-gpu-rasterization
    --enable-zero-copy
    --disk-cache-size=1073741824
    --enable-features=VaapiVideoDecoder
    --disable-features=UseChromeOSDirectVideoDecoder
    --process-per-site
  '';

  # ============================================================
  # GTK
  # ============================================================
  gtk = {
    enable = true;
    font = {
      name = "Inter";
      size = 10;
    };
    theme = {
      name = "adw-gtk3";
      package = pkgs.adw-gtk3;
    };
    iconTheme = {
      name = "Papirus";
      package = pkgs.papirus-icon-theme;
    };
    cursorTheme = {
      name = "Bibata-Modern-Classic";
      package = pkgs.bibata-cursors;
      size = 20;
    };
    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = false;
    };
  };

  # ============================================================
  # Umgebungsvariablen (~/.profile)
  # ============================================================
  home.sessionVariables = {
    XCURSOR_THEME = "Bibata-Modern-Classic";
    XCURSOR_SIZE = "20";
  };

  # ============================================================
  # XDG User Dirs
  # ============================================================
  xdg.userDirs = {
    enable = true;
    createDirectories = true;
  };

  # ============================================================
  # Cursor Theme (systemweit)
  # ============================================================
  home.pointerCursor = {
    name = "Bibata-Modern-Classic";
    package = pkgs.bibata-cursors;
    size = 20;
    gtk.enable = true;
  };

  # ============================================================
  # Skripte (~/Skripte/) — aus dem Repo deployt
  # ============================================================
  home.file."Skripte/brave_optimized.sh" = {
    source = ./skripte/brave_optimized.sh;
    executable = true;
  };
  home.file."Skripte/clipboard_cleaner.sh" = {
    source = ./skripte/clipboard_cleaner.sh;
    executable = true;
  };
  home.file."Skripte/lock.sh" = {
    source = ./skripte/lock.sh;
    executable = true;
  };
  home.file."Skripte/lockscreen.py" = {
    source = ./skripte/lockscreen.py;
    executable = true;
  };
  home.file."Skripte/monitor-lid.sh" = {
    source = ./skripte/monitor-lid.sh;
    executable = true;
  };
  home.file."Skripte/open_dejure.sh" = {
    source = ./skripte/open_dejure.sh;
    executable = true;
  };
  home.file."Skripte/projects-panel.py" = {
    source = ./skripte/projects-panel.py;
    executable = true;
  };
  home.file."Skripte/split_toggle.sh" = {
    source = ./skripte/split_toggle.sh;
    executable = true;
  };
  home.file."Skripte/theme-toggle.sh" = {
    source = ./skripte/theme-toggle.sh;
    executable = true;
  };
  home.file."Skripte/wallpaper-sysinfo.sh" = {
    source = ./skripte/wallpaper-sysinfo.sh;
    executable = true;
  };

  # ============================================================
  # git-pp (~/.local/bin/)
  # ============================================================
  home.file.".local/bin/git-pp" = {
    source = ./bin/git-pp;
    executable = true;
  };
}
