#!/bin/bash
# theme-toggle.sh — Switch between dark and light mode (monochrome)
# Usage: theme-toggle.sh [toggle|dark|light|query]

MODE_FILE="$HOME/.config/theme-mode"
CURRENT=$(cat "$MODE_FILE" 2>/dev/null || echo "dark")

case "${1:-toggle}" in
    toggle) [ "$CURRENT" = "dark" ] && MODE="light" || MODE="dark" ;;
    light|dark) MODE="$1" ;;
    query) echo "$CURRENT"; exit 0 ;;
    *) echo "Usage: $0 [toggle|dark|light|query]"; exit 1 ;;
esac

echo "$MODE" > "$MODE_FILE"

# ── Color Palette (monochrome only) ───────────────────────────
if [ "$MODE" = "dark" ]; then
    # Catppuccin Mocha — grays only
    BASE="1e1e2e"; MANTLE="181825"; CRUST="11111b"
    SURFACE0="313244"; SURFACE1="45475a"; SURFACE2="585b70"
    TEXT="cdd6f4"; SUBTEXT1="bac2de"; SUBTEXT0="a6adc8"
    OVERLAY0="6c7086"; OVERLAY1="7f849c"
    # Accent = light gray (no color)
    ACCENT="bac2de"
    GTK_THEME="adw-gtk3-dark"; GTK_DARK="true"
else
    # Catppuccin Latte — grays only
    BASE="eff1f5"; MANTLE="e6e9ef"; CRUST="dce0e8"
    SURFACE0="ccd0da"; SURFACE1="bcc0cc"; SURFACE2="acb0be"
    TEXT="4c4f69"; SUBTEXT1="5c5f77"; SUBTEXT0="6c6f85"
    OVERLAY0="9ca0b0"; OVERLAY1="8c8fa1"
    # Accent = dark gray (no color)
    ACCENT="5c5f77"
    GTK_THEME="adw-gtk3"; GTK_DARK="false"
fi

# ── Sway Theme ─────────────────────────────────────────────────
mkdir -p "$HOME/.config/sway"
cat > "$HOME/.config/sway/theme" << EOF
# Auto-generated by theme-toggle.sh — $MODE mode
client.focused          #$ACCENT #$BASE #$TEXT #$ACCENT #$ACCENT
client.focused_inactive #$SURFACE1 #$BASE #$SUBTEXT0 #$SURFACE1 #$SURFACE1
client.unfocused        #$SURFACE0 #$BASE #$SURFACE2 #$SURFACE0 #$SURFACE0
client.urgent           #$TEXT #$BASE #$TEXT #$TEXT #$TEXT
EOF

swaymsg "client.focused #$ACCENT #$BASE #$TEXT #$ACCENT #$ACCENT" 2>/dev/null || true
swaymsg "client.focused_inactive #$SURFACE1 #$BASE #$SUBTEXT0 #$SURFACE1 #$SURFACE1" 2>/dev/null || true
swaymsg "client.unfocused #$SURFACE0 #$BASE #$SURFACE2 #$SURFACE0 #$SURFACE0" 2>/dev/null || true
swaymsg "client.urgent #$TEXT #$BASE #$TEXT #$TEXT #$TEXT" 2>/dev/null || true

# ── Waybar Style (transparent, monochrome) ─────────────────────
mkdir -p "$HOME/.config/waybar"
cat > "$HOME/.config/waybar/style.css" << WCSS
/* Auto-generated by theme-toggle.sh — $MODE mode */
* {
    font-family: "Inter";
    font-size: 13px;
    border: none;
    border-radius: 0;
    min-height: 0;
    margin: 0;
    padding: 0;
}

#waybar {
    background: transparent;
    color: #${SUBTEXT1};
}

#workspaces button {
    background: transparent;
    color: #${OVERLAY0};
    padding: 0 6px;
    margin: 4px 1px;
    border-radius: 0;
    font-size: 13px;
}

#workspaces button.focused {
    color: #${TEXT};
    font-weight: 600;
}

#workspaces button.urgent {
    color: #${TEXT};
    text-decoration: underline;
}

#workspaces button:hover {
    color: #${TEXT};
}

#mode {
    color: #${TEXT};
    font-style: italic;
    padding: 0 8px;
    margin: 4px 0;
}

#clock {
    font-weight: 600;
    color: #${TEXT};
    padding: 0 12px;
    margin: 4px 2px;
}

#bluetooth,
#network,
#battery,
#custom-theme {
    padding: 0 8px;
    margin: 4px 0;
}

#network.disconnected {
    color: #${OVERLAY0};
}

#battery.charging,
#battery.plugged {
    color: #${TEXT};
}

#battery.warning:not(.charging) {
    color: #${SUBTEXT0};
    font-weight: 600;
}

#battery.critical:not(.charging) {
    color: #${TEXT};
    font-weight: 700;
}

#custom-theme {
    font-size: 15px;
    padding: 0 6px;
    margin: 4px 4px;
}

tooltip {
    background: #${BASE};
    border: 1px solid #${SURFACE1};
    border-radius: 8px;
}

tooltip label {
    color: #${TEXT};
    padding: 4px 8px;
}
WCSS

# ── Foot Terminal ──────────────────────────────────────────────
mkdir -p "$HOME/.config/foot"
cat > "$HOME/.config/foot/foot.ini" << FOOT
# Auto-generated by theme-toggle.sh — $MODE mode
[main]
font=JetBrains Mono:size=11
pad=12x12
dpi-aware=yes

[colors]
background=${BASE}
foreground=${TEXT}
cursor=${TEXT} ${BASE}

regular0=${SURFACE1}
regular1=${SUBTEXT0}
regular2=${OVERLAY1}
regular3=${SUBTEXT1}
regular4=${OVERLAY0}
regular5=${SURFACE2}
regular6=${OVERLAY1}
regular7=${SUBTEXT1}

bright0=${SURFACE2}
bright1=${TEXT}
bright2=${SUBTEXT1}
bright3=${TEXT}
bright4=${SUBTEXT0}
bright5=${OVERLAY0}
bright6=${SUBTEXT1}
bright7=${SUBTEXT0}
FOOT

# ── Rofi ───────────────────────────────────────────────────────
mkdir -p "$HOME/.config/rofi"
cat > "$HOME/.config/rofi/config.rasi" << 'ROFI_END'
/* Auto-generated by theme-toggle.sh */

configuration {
    show-icons:      true;
    display-drun:    "";
    disable-history: false;
}
ROFI_END

cat >> "$HOME/.config/rofi/config.rasi" << ROFI
* {
    font: "JetBrains Mono 12";
    foreground: #${TEXT};
    background-color: #${BASE};
    active-background: #${ACCENT};
    urgent-background: #${TEXT};
    urgent-foreground: #${BASE};
    selected-background: #${SURFACE1};
    selected-urgent-background: @urgent-background;
    selected-active-background: @active-background;
    separatorcolor: #${SURFACE0};
    bordercolor: #${ACCENT};
}

#window {
    background-color: @background-color;
    border:           2;
    border-radius:    12;
    border-color:     @bordercolor;
    padding:          20;
}
#mainbox {
    border:  0;
    padding: 0;
}
#message {
    border:       0px;
    border-color: @separatorcolor;
    padding:      1px;
}
#textbox {
    text-color: @foreground;
}
#listview {
    fixed-height: 0;
    border:       0px;
    border-color: @separatorcolor;
    spacing:      4px;
    scrollbar:    false;
    padding:      8px 0px 0px;
}
#element {
    border:  0;
    padding: 6px 8px;
    border-radius: 8;
}
#element.normal.normal {
    background-color: @background-color;
    text-color:       @foreground;
}
#element.normal.urgent {
    background-color: @urgent-background;
    text-color:       @urgent-foreground;
}
#element.normal.active {
    background-color: #${SURFACE0};
    text-color:       @foreground;
}
#element.selected.normal {
    background-color: @selected-background;
    text-color:       @foreground;
}
#element.selected.urgent {
    background-color: @selected-urgent-background;
    text-color:       @foreground;
}
#element.selected.active {
    background-color: @selected-active-background;
    text-color:       #${BASE};
}
#element.alternate.normal {
    background-color: @background-color;
    text-color:       @foreground;
}
#element.alternate.urgent {
    background-color: @urgent-background;
    text-color:       @foreground;
}
#element.alternate.active {
    background-color: #${SURFACE0};
    text-color:       @foreground;
}
#scrollbar {
    width:        2px;
    border:       0;
    handle-width: 8px;
    padding:      0;
}
#sidebar {
    border:       2px dash 0px 0px;
    border-color: @separatorcolor;
}
#button.selected {
    background-color: @selected-background;
    text-color:       @foreground;
}
#inputbar {
    spacing:    0;
    text-color: @foreground;
    padding:    4px 4px;
    border:     0 0 1px 0;
    border-color: #${SURFACE0};
}
#case-indicator {
    spacing:    0;
    text-color: @foreground;
}
#entry {
    spacing:    0;
    text-color: @foreground;
}
#prompt {
    spacing:    0;
    text-color: #${ACCENT};
}
#inputbar {
    children:   [ prompt,textbox-prompt-colon,entry,case-indicator ];
}
#textbox-prompt-colon {
    expand:     false;
    str:        ">";
    margin:     0px 0.3em 0em 0em;
    text-color: #${OVERLAY0};
}
element-text, element-icon {
    background-color: inherit;
    text-color: inherit;
}
ROFI

# ── Dunst ──────────────────────────────────────────────────────
mkdir -p "$HOME/.config/dunst"
cat > "$HOME/.config/dunst/dunstrc" << DUNST
# Auto-generated by theme-toggle.sh — $MODE mode

[global]
    follow = mouse
    width = 320
    height = (0, 120)
    origin = top-right
    offset = (12, 12)
    notification_limit = 5

    progress_bar = true
    progress_bar_height = 8
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 300

    indicate_hidden = yes
    shrink = no
    separator_height = 2
    separator_color = "#${SURFACE0}"
    padding = 16
    horizontal_padding = 16
    text_icon_padding = 16

    frame_width = 1
    frame_color = "#${SURFACE1}"
    corner_radius = 12

    sort = yes
    idle_threshold = 120

    font = Inter 10
    line_height = 0
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes

    icon_position = left
    min_icon_size = 32
    max_icon_size = 48

    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[urgency_low]
    background = "#${BASE}"
    foreground = "#${TEXT}"
    frame_color = "#${SURFACE0}"
    timeout = 5

[urgency_normal]
    background = "#${BASE}"
    foreground = "#${TEXT}"
    frame_color = "#${ACCENT}"
    timeout = 8

[urgency_critical]
    background = "#${BASE}"
    foreground = "#${TEXT}"
    frame_color = "#${TEXT}"
    timeout = 0
DUNST

# ── GTK ────────────────────────────────────────────────────────
mkdir -p "$HOME/.config/gtk-3.0"
cat > "$HOME/.config/gtk-3.0/settings.ini" << GTK
[Settings]
gtk-theme-name = ${GTK_THEME}
gtk-font-name = Inter 10
gtk-icon-theme-name = Adwaita
gtk-application-prefer-dark-theme = ${GTK_DARK}
gtk-cursor-theme-name = Adwaita
GTK

# ── Restart services ──────────────────────────────────────────
killall waybar 2>/dev/null; sleep 0.3; waybar &disown
killall dunst 2>/dev/null; sleep 0.2; dunst &disown

# Signal wallpaper script to regenerate with new colors
pkill -USR1 -f wallpaper-sysinfo.sh 2>/dev/null || true

exit 0
